"""initial migration

Revision ID: 07e6541146ac
Revises: 
Create Date: 2024-07-08 18:52:48.606380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e6541146ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('student_profile_id')
    )
    op.create_table('teacher_profiles',
    sa.Column('teacher_profile_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('phone_no', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('teacher_profile_id')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('reg_no', sa.String(length=100), nullable=True),
    sa.Column('student_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.student_profile_id'], name=op.f('fk_students_student_profile_id_student_profiles')),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('teacher_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_profile_id'], ['teacher_profiles.teacher_profile_id'], name=op.f('fk_teachers_teacher_profile_id_teacher_profiles')),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('course_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name=op.f('fk_courses_teacher_id_teachers')),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name=op.f('fk_enrollments_course_id_courses')),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('fk_enrollments_student_id_students')),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    op.drop_table('courses')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('teacher_profiles')
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
