"""empty message

Revision ID: 4ad4651a0821
Revises: 07e6541146ac
Create Date: 2024-07-09 05:58:21.197892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection


# revision identifiers, used by Alembic.
revision = '4ad4651a0821'
down_revision = '07e6541146ac'
branch_labels = None
depends_on = None


def table_exists(table_name):
    conn = op.get_bind()
    inspector = reflection.Inspector.from_engine(conn)
    return table_name in inspector.get_table_names()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if table_exists('student_profiles'):
        op.drop_table('student_profiles')
    if table_exists('enrollments'):
        op.drop_table('enrollments')
    if table_exists('students'):
        op.drop_table('students')
    if table_exists('courses'):
        op.drop_table('courses')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False, primary_key=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint('uq_teachers_email', ['email'])
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=False, primary_key=True))
        batch_op.drop_constraint('uq_teachers_email', type_='unique')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('id')

    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('course_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='fk_courses_teacher_id_teachers'),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('reg_no', sa.String(length=100), nullable=True),
    sa.Column('student_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.student_profile_id'], name='fk_students_student_profile_id_student_profiles'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name='fk_enrollments_course_id_courses'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name='fk_enrollments_student_id_students'),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.create_table('student_profiles',
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('student_profile_id')
    )
    # ### end Alembic commands ###
